### PR TITLE
feat(NavBar)

### PR DESCRIPTION
**Pull request by MaxiV95**
image
image

### CODE REVIEW

**Comment by MaxiV95** [comment]
Are the names okay?

**Review by manduinca — DISMISSED** [review]
LGTM!

**Review by FacundoPucheta — DISMISSED** [review]
Looks good to me!

**Comment by MaxiV95** [comment]
I just changed the handling of SVG icons

Ready for final review

**Comment by MaxiV95** [comment]
Ready for final review

**Review by SebaSatelier — APPROVED** [review]
Perfect!

**Review by manduinca — APPROVED** [review]
LGTM!

**Pull request merged**
